version: 2.1
commands: # a reusable command with parameters
  print_pipeline_id:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "My circle ci workflow ID <<parameters.to>>"
jobs:
  my-job:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - print_pipeline_id:
          to: $CIRCLE_WORKFLOW_ID
workflows:
  my-workflow:
    jobs:
      - my-job


