version: 2.1
commands: # a reusable command with parameters
  print_pipeline_id:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "My circle ci workflow ID <<parameters.to>>" 

  to_print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
      
# 
# an error alert check
      - run:
          name: Testing application
          command: make test
          shell: /bin/bash
          working_directory: ~/my-app
          no_output_timeout: 30m
          environment:
            FOO: bar

      - run: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts

      - run: |
          sudo -u root createuser -h localhost --superuser ubuntu &&
          sudo createdb -h localhost test_db

      - run:
          name: Upload Failed Tests
          # command: curl --data fail_tests.log http://example.com/error_logs
          command: echo "Hello Error World"
          when: on_fail
# 

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - print_pipeline_id:
          to: $CIRCLE_WORKFLOW_ID 
  my_jobs:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
workflows:
  my-workflow:
    jobs:
      - my-job
  my_workflows:
    jobs:
      - my_jobs